// AUTO-GENERATED by openapi-typescript from http://localhost:8000/openapi.json
// Regenerate: cd frontend && npm run generate-types (backend must be running)
// DO NOT EDIT manually — changes will be overwritten

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return application health status.
         *
         *     This is a lightweight application-level ping.
         *     It does not check database connectivity, external services, or dependencies.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register with email + password. Returns access and refresh tokens.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate and receive token pair.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a valid refresh token for a new token pair.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the provided refresh token. Idempotent.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Login
         * @description Redirect to Google's consent screen for OAuth login.
         */
        get: operations["google_login_auth_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Handle Google's OAuth callback. Returns JWT token pair.
         */
        get: operations["google_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Books
         * @description Browse the book catalog. Public -- no auth required.
         *
         *     Supports pagination (page/size), sorting (sort), full-text search (q),
         *     and filtering by genre (genre_id) and author. Filters combine with AND.
         *
         *     When q is present, results are sorted by relevance (ts_rank) regardless of sort param.
         */
        get: operations["list_books_books_get"];
        put?: never;
        /**
         * Create Book
         * @description Create a new book. Admin only.
         *
         *     Required: title, author, price.
         *     Optional: isbn (validated checksum), genre_id, description, cover_image_url, publish_date.
         *     409 if ISBN already exists.
         */
        post: operations["create_book_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book
         * @description Get book by ID including stock status and rating aggregates. Public -- no auth required.
         *
         *     Returns in_stock boolean (true when stock_quantity > 0).
         *     Returns avg_rating (float | None) rounded to 1 decimal place.
         *     Returns review_count (int), 0 when no reviews exist.
         *     404 if book not found.
         */
        get: operations["get_book_books__book_id__get"];
        /**
         * Update Book
         * @description Update book fields. Admin only.
         *
         *     All fields optional -- only provided fields are updated.
         *     404 if book not found. 409 if ISBN conflicts with existing book.
         */
        put: operations["update_book_books__book_id__put"];
        post?: never;
        /**
         * Delete Book
         * @description Delete a book permanently. Admin only.
         *
         *     Hard delete -- Phase 4 has no FK references to books from other tables yet.
         *     404 if book not found.
         */
        delete: operations["delete_book_books__book_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Stock
         * @description Set absolute stock quantity. Admin only.
         *
         *     When stock transitions from 0 to >0, all waiting pre-bookings are atomically
         *     notified (status set to 'notified' with notified_at timestamp).
         *     Enqueues restock alert emails for all notified users via BackgroundTasks.
         *
         *     quantity >= 0 enforced by Pydantic (ge=0) and DB CHECK CONSTRAINT.
         *     404 if book not found.
         */
        patch: operations["update_stock_books__book_id__stock_patch"];
        trace?: never;
    };
    "/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Genres
         * @description List all genres alphabetically. Public -- no auth required.
         *
         *     Genres are reference data. Empty list if no genres yet.
         */
        get: operations["list_genres_genres_get"];
        put?: never;
        /**
         * Create Genre
         * @description Create a new genre. Admin only.
         *
         *     409 if genre name already exists (case-sensitive).
         */
        post: operations["create_genre_genres_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cart
         * @description Return the authenticated user's cart.
         *
         *     Returns empty items list (not 404) when the user has no cart yet.
         */
        get: operations["get_cart_cart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Cart Item
         * @description Add a book to the user's cart.
         *
         *     409 CART_BOOK_OUT_OF_STOCK if book has no stock.
         *     409 CART_ITEM_DUPLICATE if book is already in the cart.
         *     404 BOOK_NOT_FOUND if the book does not exist.
         */
        post: operations["add_cart_item_cart_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Cart Item
         * @description Update the quantity of a cart item.
         *
         *     404 CART_ITEM_NOT_FOUND if item does not exist.
         *     403 CART_ITEM_FORBIDDEN if item belongs to another user.
         */
        put: operations["update_cart_item_cart_items__item_id__put"];
        post?: never;
        /**
         * Remove Cart Item
         * @description Remove an item from the user's cart.
         *
         *     404 CART_ITEM_NOT_FOUND if item does not exist.
         *     403 CART_ITEM_FORBIDDEN if item belongs to another user.
         */
        delete: operations["remove_cart_item_cart_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout
         * @description Convert the authenticated user's cart into a confirmed order.
         *
         *     422 ORDER_CART_EMPTY if cart is empty.
         *     409 ORDER_INSUFFICIENT_STOCK if any item lacks stock.
         *     402 ORDER_PAYMENT_FAILED if payment is declined.
         */
        post: operations["checkout_orders_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orders
         * @description Return the authenticated user's order history with line items.
         */
        get: operations["list_orders_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Order
         * @description Return a specific order owned by the authenticated user.
         *
         *     404 ORDER_NOT_FOUND if order does not exist or belongs to another user.
         */
        get: operations["get_order_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Orders
         * @description Return all orders across all users (admin only).
         */
        get: operations["list_all_orders_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wishlist
         * @description Return the authenticated user's wishlist with current book price and stock.
         */
        get: operations["get_wishlist_wishlist_get"];
        put?: never;
        /**
         * Add To Wishlist
         * @description Add a book to the authenticated user's wishlist.
         *
         *     409 WISHLIST_ITEM_DUPLICATE if the book is already on the wishlist.
         *     404 BOOK_NOT_FOUND if the book does not exist.
         */
        post: operations["add_to_wishlist_wishlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlist/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove From Wishlist
         * @description Remove a book from the authenticated user's wishlist.
         *
         *     404 WISHLIST_ITEM_NOT_FOUND if the book is not on the wishlist.
         */
        delete: operations["remove_from_wishlist_wishlist__book_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pre Bookings
         * @description Return all pre-bookings for the authenticated user (all statuses, newest first).
         */
        get: operations["list_pre_bookings_prebooks_get"];
        put?: never;
        /**
         * Create Pre Booking
         * @description Reserve an out-of-stock book for the authenticated user.
         *
         *     409 PREBOOK_BOOK_IN_STOCK if book has stock > 0 (add to cart instead).
         *     409 PREBOOK_DUPLICATE if user already has an active pre-booking for this book.
         *     404 BOOK_NOT_FOUND if book does not exist.
         */
        post: operations["create_pre_booking_prebooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prebooks/{prebook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel Pre Booking
         * @description Cancel (soft-delete) a pre-booking. Sets status to CANCELLED.
         *
         *     404 PREBOOK_NOT_FOUND if not found or belongs to another user.
         *     409 PREBOOK_ALREADY_CANCELLED if already cancelled.
         */
        delete: operations["cancel_pre_booking_prebooks__prebook_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Return a paginated list of all users. Admin only.
         *
         *     Supports optional filtering by role and/or is_active status.
         *     Results are sorted by created_at DESC (newest first).
         */
        get: operations["list_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Deactivate User
         * @description Deactivate a user account and revoke all their refresh tokens. Admin only.
         *
         *     403 ADMN_CANNOT_DEACTIVATE_ADMIN if target user is an admin.
         *     404 USER_NOT_FOUND if user does not exist.
         *     Idempotent: returns 200 if user is already deactivated.
         */
        patch: operations["deactivate_user_admin_users__user_id__deactivate_patch"];
        trace?: never;
    };
    "/admin/users/{user_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reactivate User
         * @description Reactivate a previously deactivated user account. Admin only.
         *
         *     404 USER_NOT_FOUND if user does not exist.
         *     Idempotent: returns 200 if user is already active.
         */
        patch: operations["reactivate_user_admin_users__user_id__reactivate_patch"];
        trace?: never;
    };
    "/admin/analytics/sales/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sales Summary
         * @description Return revenue summary for the given period with period-over-period delta.
         *
         *     Period options:
         *     - today: Current day from UTC midnight to now.
         *     - week: Current ISO week (Monday 00:00 UTC to now).
         *     - month: Current month (1st 00:00 UTC to now).
         *
         *     Response fields:
         *     - revenue: Total revenue from CONFIRMED orders (float, 2dp).
         *     - order_count: Number of distinct CONFIRMED orders.
         *     - aov: Average order value (0.0 when no orders).
         *     - delta_percentage: % change vs previous full period (null when prior revenue is 0).
         *
         *     Admin only. Invalid period values return 422.
         */
        get: operations["get_sales_summary_admin_analytics_sales_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/analytics/sales/top-books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top Books
         * @description Return top-selling books ranked by revenue or volume.
         *
         *     Query parameters:
         *     - sort_by: "revenue" (default) or "volume" — determines ranking dimension.
         *     - limit: Number of books to return (1-50, default 10).
         *
         *     Only CONFIRMED orders are counted. Deleted books are excluded.
         *     Admin only. Invalid sort_by values return 422.
         */
        get: operations["get_top_books_admin_analytics_sales_top_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/analytics/inventory/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Low Stock Books
         * @description Return all books with stock at or below the threshold, ordered by stock ascending.
         *
         *     Query parameters:
         *     - threshold: Inclusive stock level cutoff (default 10, minimum 0).
         *
         *     Zero-stock books appear at the top of the list. Admin only. threshold < 0 returns 422.
         */
        get: operations["get_low_stock_books_admin_analytics_inventory_low_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description Return paginated, filtered list of all non-deleted reviews for admin moderation.
         *
         *     Query parameters:
         *     - page: Page number (default 1, minimum 1).
         *     - per_page: Items per page (default 20, 1-100).
         *     - book_id: Filter by book ID (optional).
         *     - user_id: Filter by user ID (optional).
         *     - rating_min: Minimum rating 1-5 inclusive (optional).
         *     - rating_max: Maximum rating 1-5 inclusive (optional).
         *     - sort_by: "date" (default) or "rating".
         *     - sort_dir: "desc" (default) or "asc".
         *
         *     Filters combine as AND. Admin only. Invalid values return 422.
         */
        get: operations["list_reviews_admin_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reviews/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Bulk Delete Reviews
         * @description Bulk soft-delete reviews by ID list.
         *
         *     Accepts up to 50 review IDs. Best-effort: silently skips IDs that are
         *     missing or already soft-deleted. Returns count of actually deleted reviews.
         *
         *     Admin only. Empty list or >50 IDs returns 422.
         */
        delete: operations["bulk_delete_reviews_admin_reviews_bulk_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description Return paginated reviews for a book.
         *
         *     Public endpoint — no authentication required.
         *     Each review includes a verified_purchase flag indicating confirmed purchase.
         */
        get: operations["list_reviews_books__book_id__reviews_get"];
        put?: never;
        /**
         * Create Review
         * @description Create a review for a book.
         *
         *     Requires authentication. The user must have a confirmed purchase of the book.
         *
         *     403 NOT_PURCHASED if the user has not purchased the book.
         *     404 BOOK_NOT_FOUND if the book does not exist.
         *     409 DUPLICATE_REVIEW if the user has already reviewed this book (includes existing_review_id).
         */
        post: operations["create_review_books__book_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description Return a single review by ID.
         *
         *     Public endpoint — no authentication required.
         *     404 REVIEW_NOT_FOUND if the review does not exist or has been soft-deleted.
         */
        get: operations["get_review_reviews__review_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Review
         * @description Soft-delete a review.
         *
         *     Review owners can delete their own review. Admins can delete any review.
         *     The same endpoint handles both user and admin deletion — the service checks
         *     ownership and grants admin bypass via the is_admin flag.
         *
         *     403 NOT_REVIEW_OWNER if the requesting user is not the owner and is not admin.
         *     404 REVIEW_NOT_FOUND if the review does not exist or has been soft-deleted.
         */
        delete: operations["delete_review_reviews__review_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Review
         * @description Update a review's rating and/or text.
         *
         *     Only the review owner can update their review.
         *
         *     Uses model_fields_set to distinguish fields the client explicitly sent from
         *     those that were omitted (which should not be updated).
         *
         *     403 NOT_REVIEW_OWNER if the requesting user is not the review author.
         *     404 REVIEW_NOT_FOUND if the review does not exist or has been soft-deleted.
         */
        patch: operations["update_review_reviews__review_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminReviewAuthor
         * @description Reviewer identity in the admin moderation list.
         */
        AdminReviewAuthor: {
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
        };
        /**
         * AdminReviewBook
         * @description Book context in the admin moderation list.
         */
        AdminReviewBook: {
            /** Book Id */
            book_id: number;
            /** Title */
            title: string;
        };
        /**
         * AdminReviewEntry
         * @description Single review in the admin moderation list.
         *
         *     Omits verified_purchase (admin concern is content, not purchase status).
         *     Omits avatar_url and cover_image_url (not needed for moderation).
         */
        AdminReviewEntry: {
            /** Id */
            id: number;
            /** Rating */
            rating: number;
            /** Text */
            text: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            author: components["schemas"]["AdminReviewAuthor"];
            book: components["schemas"]["AdminReviewBook"];
        };
        /**
         * AdminReviewListResponse
         * @description Paginated envelope for admin review list — follows admin convention.
         */
        AdminReviewListResponse: {
            /** Items */
            items: components["schemas"]["AdminReviewEntry"][];
            /** Total Count */
            total_count: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * AdminUserResponse
         * @description Admin view of a user account.
         */
        AdminUserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BookCreate
         * @description Request body for POST /books. title, author, price are required.
         */
        BookCreate: {
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Price */
            price: number | string;
            /** Isbn */
            isbn?: string | null;
            /** Genre Id */
            genre_id?: number | null;
            /** Description */
            description?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /** Publish Date */
            publish_date?: string | null;
        };
        /**
         * BookDetailResponse
         * @description Response for GET /books/{id} -- extends BookResponse with computed in_stock field.
         *
         *     in_stock is a derived boolean (stock_quantity > 0) -- not stored in DB.
         *     stock_quantity is still included for admin-facing clients that need the exact count.
         *     avg_rating and review_count are computed live from reviews (AGGR-01, AGGR-02).
         */
        BookDetailResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Price */
            price: string;
            /** Isbn */
            isbn: string | null;
            /** Genre Id */
            genre_id: number | null;
            /** Description */
            description: string | null;
            /** Cover Image Url */
            cover_image_url: string | null;
            /** Publish Date */
            publish_date: string | null;
            /** Stock Quantity */
            stock_quantity: number;
            /** Avg Rating */
            avg_rating?: number | null;
            /**
             * Review Count
             * @default 0
             */
            review_count: number;
            /**
             * In Stock
             * @description True when at least one copy is available.
             */
            readonly in_stock: boolean;
        };
        /**
         * BookListResponse
         * @description Paginated book list response envelope for GET /books.
         */
        BookListResponse: {
            /** Items */
            items: components["schemas"]["BookResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * BookResponse
         * @description Response schema for book records.
         */
        BookResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Price */
            price: string;
            /** Isbn */
            isbn: string | null;
            /** Genre Id */
            genre_id: number | null;
            /** Description */
            description: string | null;
            /** Cover Image Url */
            cover_image_url: string | null;
            /** Publish Date */
            publish_date: string | null;
            /** Stock Quantity */
            stock_quantity: number;
        };
        /**
         * BookUpdate
         * @description Request body for PUT /books/{id}. All fields optional.
         */
        BookUpdate: {
            /** Title */
            title?: string | null;
            /** Author */
            author?: string | null;
            /** Price */
            price?: number | string | null;
            /** Isbn */
            isbn?: string | null;
            /** Genre Id */
            genre_id?: number | null;
            /** Description */
            description?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /** Publish Date */
            publish_date?: string | null;
        };
        /**
         * BulkDeleteRequest
         * @description Request body for bulk review soft-delete.
         *
         *     Max 50 IDs per request — locked user decision.
         *     min_length=1 prevents empty list submission.
         */
        BulkDeleteRequest: {
            /** Review Ids */
            review_ids: number[];
        };
        /**
         * BulkDeleteResponse
         * @description Response for bulk review soft-delete.
         *
         *     deleted_count reflects only reviews actually soft-deleted
         *     (best-effort: missing or already-deleted IDs silently skipped).
         */
        BulkDeleteResponse: {
            /** Deleted Count */
            deleted_count: number;
        };
        /**
         * CartItemAdd
         * @description Request body for POST /cart/items.
         */
        CartItemAdd: {
            /** Book Id */
            book_id: number;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /**
         * CartItemResponse
         * @description Response schema for a single cart item.
         */
        CartItemResponse: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Quantity */
            quantity: number;
            book: components["schemas"]["app__cart__schemas__BookSummary"];
        };
        /**
         * CartItemUpdate
         * @description Request body for PUT /cart/items/{item_id}.
         */
        CartItemUpdate: {
            /** Quantity */
            quantity: number;
        };
        /**
         * CartResponse
         * @description Response schema for GET /cart — full cart with computed totals.
         */
        CartResponse: {
            /** Items */
            items: components["schemas"]["CartItemResponse"][];
            /**
             * Total Items
             * @description Sum of all item quantities.
             */
            readonly total_items: number;
            /**
             * Total Price
             * @description Sum of (book.price * quantity) for all items.
             */
            readonly total_price: string;
        };
        /**
         * CheckoutRequest
         * @description Request body for POST /orders/checkout.
         */
        CheckoutRequest: {
            /**
             * Force Payment Failure
             * @default false
             */
            force_payment_failure: boolean;
        };
        /**
         * GenreCreate
         * @description Request body for POST /genres.
         */
        GenreCreate: {
            /** Name */
            name: string;
        };
        /**
         * GenreResponse
         * @description Response schema for genre records.
         */
        GenreResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description POST /auth/login request body.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LowStockBookEntry
         * @description Single book entry in the low-stock inventory report.
         *
         *     threshold is echoed per-item per locked decision — allows dashboard to show
         *     "5 units (threshold: 10)" without a second API call.
         */
        LowStockBookEntry: {
            /** Book Id */
            book_id: number;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Current Stock */
            current_stock: number;
            /** Threshold */
            threshold: number;
        };
        /**
         * LowStockResponse
         * @description Response schema for GET /admin/analytics/inventory/low-stock.
         */
        LowStockResponse: {
            /** Threshold */
            threshold: number;
            /** Total Low Stock */
            total_low_stock: number;
            /** Items */
            items: components["schemas"]["LowStockBookEntry"][];
        };
        /**
         * OrderItemBookSummary
         * @description Minimal book info embedded in order item responses.
         */
        OrderItemBookSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Author */
            author: string;
        };
        /**
         * OrderItemResponse
         * @description Response schema for a single order item.
         */
        OrderItemResponse: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number | null;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            book: components["schemas"]["OrderItemBookSummary"] | null;
        };
        /**
         * OrderResponse
         * @description Response schema for an order with all line items.
         */
        OrderResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["OrderItemResponse"][];
            /**
             * Total Price
             * @description Sum of (unit_price * quantity) for all items.
             */
            readonly total_price: string;
        };
        /**
         * PreBookCreate
         * @description Request body for POST /prebooks.
         */
        PreBookCreate: {
            /**
             * Book Id
             * @description ID of the book to pre-book
             */
            book_id: number;
        };
        /**
         * PreBookListResponse
         * @description Response envelope for GET /prebooks.
         */
        PreBookListResponse: {
            /** Items */
            items: components["schemas"]["PreBookResponse"][];
        };
        /**
         * PreBookResponse
         * @description Response schema for a single pre-booking.
         */
        PreBookResponse: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Book Title */
            book_title: string;
            /** Book Author */
            book_author: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Notified At */
            notified_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
        };
        /**
         * RefreshRequest
         * @description POST /auth/refresh and POST /auth/logout request body.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * ReviewAuthorSummary
         * @description Nested author summary embedded in every ReviewResponse.
         *
         *     display_name is derived from email (email.split('@')[0]) since
         *     the User model has no display_name column.
         *     avatar_url is always None until a profile feature is added.
         */
        ReviewAuthorSummary: {
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /**
         * ReviewBookSummary
         * @description Nested book summary embedded in every ReviewResponse.
         *
         *     book_id maps to Book.id — constructed explicitly by the service
         *     because the field name differs from the ORM attribute.
         */
        ReviewBookSummary: {
            /** Book Id */
            book_id: number;
            /** Title */
            title: string;
            /** Cover Image Url */
            cover_image_url: string | null;
        };
        /**
         * ReviewCreate
         * @description Request body for POST /books/{book_id}/reviews.
         */
        ReviewCreate: {
            /** Rating */
            rating: number;
            /** Text */
            text?: string | null;
        };
        /**
         * ReviewListResponse
         * @description Paginated review list response envelope for GET /books/{book_id}/reviews.
         */
        ReviewListResponse: {
            /** Items */
            items: components["schemas"]["ReviewResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * ReviewResponse
         * @description Full review response including nested author and book summaries.
         *
         *     verified_purchase is NOT on the ORM model — it is injected by the service
         *     via _build_review_data() and validated from a plain dict.
         */
        ReviewResponse: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** User Id */
            user_id: number;
            /** Rating */
            rating: number;
            /** Text */
            text: string | null;
            /** Verified Purchase */
            verified_purchase: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            author: components["schemas"]["ReviewAuthorSummary"];
            book: components["schemas"]["ReviewBookSummary"];
        };
        /**
         * ReviewUpdate
         * @description Request body for PATCH /reviews/{review_id}.
         *
         *     All fields are optional — only provided fields are updated.
         *     Defined here for use in Plan 14-02.
         */
        ReviewUpdate: {
            /** Rating */
            rating?: number | null;
            /** Text */
            text?: string | null;
        };
        /**
         * SalesSummaryResponse
         * @description Response schema for GET /admin/analytics/sales/summary.
         *
         *     All money fields are float (not Decimal) — Pydantic v2 serializes Decimal as
         *     string by default, which would break JSON clients expecting numeric values.
         */
        SalesSummaryResponse: {
            /** Period */
            period: string;
            /** Revenue */
            revenue: number;
            /** Order Count */
            order_count: number;
            /** Aov */
            aov: number;
            /** Delta Percentage */
            delta_percentage: number | null;
        };
        /**
         * StockUpdate
         * @description Request body for PATCH /books/{id}/stock.
         */
        StockUpdate: {
            /**
             * Quantity
             * @description Absolute stock quantity to set
             */
            quantity: number;
        };
        /**
         * TokenResponse
         * @description Response for register, login, and refresh endpoints.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TopBookEntry
         * @description Single book entry in the top-books ranking.
         *
         *     total_revenue is float (same pattern as SalesSummaryResponse) to avoid
         *     Pydantic v2 Decimal-as-string serialization.
         */
        TopBookEntry: {
            /** Book Id */
            book_id: number;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Total Revenue */
            total_revenue: number;
            /** Units Sold */
            units_sold: number;
        };
        /**
         * TopBooksResponse
         * @description Response schema for GET /admin/analytics/sales/top-books.
         */
        TopBooksResponse: {
            /** Sort By */
            sort_by: string;
            /** Items */
            items: components["schemas"]["TopBookEntry"][];
        };
        /**
         * UserCreate
         * @description POST /auth/register request body.
         *
         *     NOTE: No 'role' field — registration always creates user role.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserListResponse
         * @description Paginated envelope for admin user list.
         */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["AdminUserResponse"][];
            /** Total Count */
            total_count: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WishlistAdd
         * @description Request body for POST /wishlist.
         */
        WishlistAdd: {
            /** Book Id */
            book_id: number;
        };
        /**
         * WishlistItemResponse
         * @description Response schema for a single wishlist item.
         */
        WishlistItemResponse: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            book: components["schemas"]["app__wishlist__schemas__BookSummary"];
        };
        /**
         * WishlistResponse
         * @description Response schema for GET /wishlist — full wishlist with all saved books.
         */
        WishlistResponse: {
            /** Items */
            items: components["schemas"]["WishlistItemResponse"][];
        };
        /**
         * BookSummary
         * @description Minimal book info embedded in cart item responses.
         */
        app__cart__schemas__BookSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Price */
            price: string;
            /** Cover Image Url */
            cover_image_url: string | null;
        };
        /**
         * BookSummary
         * @description Minimal book info embedded in wishlist item responses.
         */
        app__wishlist__schemas__BookSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Price */
            price: string;
            /** Stock Quantity */
            stock_quantity: number;
            /** Cover Image Url */
            cover_image_url: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_auth_google_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    list_books_books_get: {
        parameters: {
            query?: {
                /** @description Full-text search across title and author */
                q?: string | null;
                /** @description Filter by genre ID (from GET /genres) */
                genre_id?: number | null;
                /** @description Filter by author name (case-insensitive partial match) */
                author?: string | null;
                /** @description Sort order: title (A-Z), price (asc), date (publish_date asc), created_at (newest first) */
                sort?: "title" | "price" | "date" | "created_at";
                /** @description Page number, 1-indexed */
                page?: number;
                /** @description Items per page (max 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_book_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_book_books__book_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_books__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stock_books__book_id__stock_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_genres_genres_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreResponse"][];
                };
            };
        };
    };
    create_genre_genres_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenreCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    add_cart_item_cart_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cart_item_cart_items__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_cart_item_cart_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkout_orders_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
        };
    };
    get_order_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_orders_admin_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
        };
    };
    get_wishlist_wishlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistResponse"];
                };
            };
        };
    };
    add_to_wishlist_wishlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_wishlist_wishlist__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pre_bookings_prebooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreBookListResponse"];
                };
            };
        };
    };
    create_pre_booking_prebooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreBookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreBookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_pre_booking_prebooks__prebook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prebook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                role?: components["schemas"]["UserRole"] | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_admin_users__user_id__deactivate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_user_admin_users__user_id__reactivate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_summary_admin_analytics_sales_summary_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_books_admin_analytics_sales_top_books_get: {
        parameters: {
            query?: {
                sort_by?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopBooksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_low_stock_books_admin_analytics_inventory_low_stock_get: {
        parameters: {
            query?: {
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LowStockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_admin_reviews_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                book_id?: number | null;
                user_id?: number | null;
                rating_min?: number | null;
                rating_max?: number | null;
                sort_by?: string;
                sort_dir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_reviews_admin_reviews_bulk_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_books__book_id__reviews_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_books__book_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_review_reviews__review_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_review_reviews__review_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
